# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/dsi-principles-prog-F2023',
                'doc_host': 'https://dsi-principles-prog-F2023.github.io',
                'git_url': 'https://github.com/dsi-principles-prog-F2023/ai-assisted-coding-final',
                'lib_path': 'ai_assisted_coding_final'},
  'syms': {'ai_assisted_coding_final.core': {'ai_assisted_coding_final.core.foo': ('core.html#foo', 'ai_assisted_coding_final/core.py')}}}
