# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/ask-the-dataset.ipynb.

# %% auto 0
__all__ = ['ask_gpt']

# %% ../nbs/ask-the-dataset.ipynb 1
import pandas as pd
import os
import getpass
import openai
from openai import OpenAI
import gradio as gr
from io import StringIO

# %% ../nbs/ask-the-dataset.ipynb 6
def ask_gpt(question,csv_summary):
    client = OpenAI()

    response = client.chat.completions.create(
    model="gpt-3.5-turbo",
    messages=[
            {"role": "system", "content": "You are a helpful assistant. Here is the data you need to read: " + csv_summary},
            {"role": "user", "content": question}
        ])
    
    return response.choices[0].message.content
    
