# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/02_ask-the-dataset.ipynb.

# %% auto 0
__all__ = ['CSVFileManager', 'GPTQuestionsHandler', 'main']

# %% ../nbs/02_ask-the-dataset.ipynb 3
import pandas as pd
import os
import getpass
import openai
from openai import OpenAI
import gradio as gr
from io import StringIO
import sys

# %% ../nbs/02_ask-the-dataset.ipynb 4
class CSVFileManager:
    """This class is responsible for handling CSV file operations. 
    It can read one or more CSV files, either from file paths or file-like objects, and concatenate them into a
    single pandas DataFrame.
    """
    def __init__(self):
        self.data_frame = None

    def load_data(self, files):
        
        if not files:
            raise ValueError("No files provided.")

        data_frames = []
        for file in files:
            # Check if the file is a string (path) or a file-like object
            if isinstance(file, str):
                df = pd.read_csv(file)
            else:  # Assuming file-like object
                df = pd.read_csv(file)
            data_frames.append(df)

        self.data_frame = pd.concat(data_frames, ignore_index=True)
        return self.data_frame

class GPTQuestionsHandler:
    """This class interfaces with OpenAI's GPT model. 
    It sends user queries about the dataset to the GPT model and retrieves responses.
    """
    
    def __init__(self, api_key):

        # Initializes the OpenAI API client

        self.api_key = api_key
        os.environ["OPENAI_API_KEY"] = api_key
        self.client = OpenAI()

    def ask_gpt(self, question, data):
        """
        Sends a question and data to the OpenAI API and retrieves the response
        Arguments: The user's question about the data
        Data is input to the model in string format
        Model returns the response from the API
        """

        system_message = ("You are a helpful assistant skilled at data science and data analysis. "
                          "You are an expert at reading files, interpreting them and also writing python codes. "
                          "Here is the data you need to work with:\n" + data)
        response = self.client.chat.completions.create(
            model="gpt-3.5-turbo-1106",
            temperature=1,
            max_tokens=320,
            top_p=1,
            frequency_penalty=0,
            presence_penalty=0,
            messages=[
                {"role": "system", "content": system_message},
                {"role": "user", "content": question}
            ])
        return response.choices[0].message.content


# %% ../nbs/02_ask-the-dataset.ipynb 5
def main():
    try:
        file_paths_input = input("Enter CSV file paths, separated by a comma: ")
        file_paths = [path.strip() for path in file_paths_input.split(',')]
    except:
        file_paths = ['../data/009-1.csv']

    data_manager = CSVFileManager()
    data_frame = data_manager.load_data(file_paths)

    api_key = getpass.getpass("Enter OpenAI API Key: ")
    ai_handler = GPTQuestionsHandler(api_key)


    try:
        user_question = input("Please enter your question about the data: ")
        answer = ai_handler.ask_gpt(user_question, data_frame.to_string(index=False))

        print("Question: ", user_question,"\n")
        print("Answer:", answer, "\n")
    except:
        print("An error occurred. Please try again.")


if __name__ == "__main__":
    main()

